Initialize new build based on Next.JS

diff --git a/config/etc/init.d/sprinkler b/config/etc/init.d/sprinkler
--- a/config/etc/init.d/sprinkler
+++ b/config/etc/init.d/sprinkler
@@ -1,98 +1,106 @@
-#! /bin/sh
+#! /bin/bash
 ### BEGIN INIT INFO
 # Provides:          sprinkler
-# Required-Start:    $all
-# Required-Stop:     $remote_fs $syslog $network
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Sprinkler Switch web application
-# Description:       A Python Bottle web application to control irrigation systems
+# Short-Description: Sets water sensor state for irrigation system
+# Description:       Sets water sensor state for irrigation system
 ### END INIT INFO
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="Sprinkler Switch WebApp"
-NAME=run_server.py
-DAEMON=/srv/sprinkler/$NAME
-PIDFILE=/var/run/sprinkler.pid
-DAEMON_ARGS=""
+DESC="Sets water sensor state for irrigation system"
+NAME='sprinkler'
+DAEMON='/usr/bin/raspi-gpio'
+PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+APPDIR=/opt/sprinkler
 
+# Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
 
+# Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
+DAEMON_ARGS="set 23"
 
+# Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
 
+#
+# Function that starts the daemon/service
+#
 do_start()
 {
-	start-stop-daemon --start --quiet --background --make-pidfile --chuid pi --user pi --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --background --make-pidfile --chuid pi --user pi --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+  $DAEMON $DAEMON_ARGS op
+  $DAEMON $DAEMON_ARGS dl
+  $DAEMON $DAEMON_ARGS dh
 }
 
+#
+# Function that stops the daemon/service
+#
 do_stop()
 {
-	start-stop-daemon --stop --quiet --user pi --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	start-stop-daemon --stop --quiet --oknodo --user pi --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-
-	rm -f $PIDFILE
-	return "$RETVAL"
+  $DAEMON $DAEMON_ARGS op
+  $DAEMON $DAEMON_ARGS dl
 }
 
-do_reload() {
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload()
+{
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+  return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+  do_start
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
+  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+  ;;
   restart|force-reload)
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1)
+    do_start
+    case "$?" in
+      0) log_end_msg 0 ;;
+      1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
+    ;;
+    *)
+    # Failed to stop
+    log_end_msg 1
+    ;;
+  esac
+  ;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+  exit 3
+  ;;
 esac
 
 :
